# Generated by Django 4.2.30 on 2026-05-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g. Hoodies, Posters, Figures, Keychains).', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier — auto-filled in admin.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description shown on the category page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full product name (e.g. 'Naruto Hokage Hoodie').", max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier — auto-filled in admin.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description shown on the product page.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price in INR (e.g. 499.00).', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of units currently available.')),
                ('image', models.ImageField(blank=True, help_text='Product thumbnail — stored under MEDIA_ROOT/products/.', null=True, upload_to='products/')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to hide the product from the storefront.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was first added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update.')),
                ('category', models.ForeignKey(help_text='The category this product belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
