# Generated by Django 6.0.5 on 2026-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprecord',
            options={'verbose_name': 'OTP Record', 'verbose_name_plural': 'OTP Records'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='email',
            field=models.EmailField(help_text='Email address awaiting verification', max_length=254),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='expires_at',
            field=models.DateTimeField(help_text='When this OTP expires'),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='otp_hash',
            field=models.CharField(help_text='Hashed OTP value', max_length=64),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='pending_name',
            field=models.CharField(blank=True, help_text='Name from registration form (pending verification)', max_length=200),
        ),
        migrations.AlterField(
            model_name='otprecord',
            name='pending_password',
            field=models.CharField(blank=True, help_text='Hashed password from registration form (pending verification)', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text="User's email address (login identifier)", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth ID if user signed up via Google', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the user account is active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Whether the user has admin privileges'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their email via OTP'),
        ),
    ]
