# Generated by Django 6.0.5 on 2026-06-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otprecord_options_alter_user_options_and_more'),
        ('accounts', '0002_migrate_password_hash_to_password'),
    ]

    operations = [
    ]
